categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'
    changelog: |
      ## 🚀 New Features
      $CHANGES

  - title: '🐞 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
    changelog: |
      ## 🐞 Bug Fixes
      $CHANGES

  - title: '🏃 Chores'
    labels:
      - 'chore'
      - 'cleanup'
    changelog: |
      ## 🏃 Chores
      $CHANGES

  - title: '🧪 Tests'
    labels:
      - 'tests'
    changelog: |
      ## 🧪 Tests  
      $CHANGES

  - title: '🎁 CI/CD'
    labels:
      - 'cicd'
    changelog: |
      ## 🎁 CI/CD
      $CHANGES

  - title: '✨ Refactored'
    labels:
      - 'refactor'
    changelog: |
      ## ✨ Refactored
      $CHANGES

  - title: '📖 Documentation'
    labels:
      - 'docs'
    changelog: |
      ## 📖 Documentation
      $CHANGES

template: |
  $CATEGORY_CONTENTS
