categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐞 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'

  - title: '🏃 Chores'
    labels:
      - 'chore'
      - 'cleanup'

  - title: '🧪 Tests'
    labels:
      - 'tests'

  - title: '🎁 CI/CD'
    labels:
      - 'cicd'

  - title: '✨ Refactored'
    labels:
      - 'refactor'

  - title: '📖 Documentation'
    labels:
      - 'docs'

template: |
  {% for category in categories %}
  {% if category.pull_requests | length > 0 %}
  ## {{ category.title }}
  {{ category.pull_requests | join('\n') }}
  {% endif %}
  {% endfor %}