name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐞 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'

  - title: '🏃 Chores'
    labels:
      - 'chore'
      - 'cleanup'

  - title: '🧪 Tests'
    labels:
      - 'tests'

  - title: '🎁 CI/CD'
    labels:
      - 'cicd'

  - title: '✨ Refactored'
    labels:
      - 'refactor'

  - title: '📖 Documentation'
    labels:
      - 'docs'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '* No changes in this release.'
template: |
  ## What's Changed

  $CHANGES
