
# @name = createTask
POST {{todoUrl}}
Content-Type: application/json

{
  "title": "Pay bills",
  "description": "Pay all the utility bills",
  "dueDate": "2024-06-10T00:00:00"
}

###

# @name = invalidTask
POST {{todoUrl}}
Content-Type: application/json

{
  "invalid": "blah!"
}

###

# @name getAll
GET {{todoUrl}}
Accept: application/json

###

# @name getLastCreated
GET {{todoUrl}}/0461F4DBCB814ABD83458BED10F72168
Accept: application/json