name: create_release_for_pull_request
concurrency: create_release_for_pull_request

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  generateversionnumber:
    name: Generate Version Number
    runs-on: ubuntu-latest
    steps:
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    
    outputs:
      VersionNumber: ${{ env.BUILD_VERSION }}
  
  buildandpublish:    
    name: Build and Publish    
    needs:
      - generateversionnumber
    uses: ./.github/workflows/build-and-publish-artifacts.yml
    with:      
      versionNumber: ${{ needs.generateversionnumber.outputs.VersionNumber }}

  DEV:
    name: DEV
    needs:
      - generateversionnumber
      - buildandpublish
    uses: ./.github/workflows/deploy.yml
    with:
      applicationName: funky-iso
      location: australiasoutheast
      versionNumber: ${{ needs.generateversionnumber.outputs.VersionNumber }}
      environment: dev
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}