name: Create Release for PR
concurrency: Create Release for PR

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  ci_validations:    
    name: CI Validations
    uses: ./.github/workflows/ci-validation-checks.yml
  
  generate_version_number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    needs: 
      - ci_validations
    steps:
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    
    outputs:
      VersionNumber: ${{ env.BUILD_VERSION }}
  
  build_and_publish:    
    name: Build and Publish    
    needs:
      - generate_version_number
    uses: ./.github/workflows/build-and-publish-artifacts.yml
    with:      
      versionNumber: ${{ needs.generate_version_number.outputs.VersionNumber }}

  DEV:
    name: DEV
    needs:
      - generate_version_number
      - build_and_publish
    uses: ./.github/workflows/deploy.yml
    with:
      applicationName: funky-iso
      location: australiasoutheast
      versionNumber: ${{ needs.generate_version_number.outputs.VersionNumber }}
      environment: dev
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}