name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
        
jobs:
  release:
    name: Tag and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
        
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BRANCH: main
          DEFAULT_BUMP: ${{ inputs.release_type }}
          
      - name: Generate release notes with Release Drafter
        id: generate_release_notes
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ steps.bump.outputs.new_tag }}
          version: ${{ steps.bump.outputs.new_tag }}
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.bump.outputs.new_tag }}
#          release_name: ${{ steps.bump.outputs.new_tag }}
#          body: ${{ steps.generate_release_notes.outputs.body }}
#          draft: false
#          prerelease: false       
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: false
          tag: ${{ steps.bump.outputs.new_tag }}
          body: ${{ steps.generate_release_notes.outputs.body }}
    outputs:
      VersionNumber: ${{ steps.bump.outputs.new_tag }}

  buildandpublish:
    name: Build and Publish
    needs:
      - release
    uses: ./.github/workflows/build-and-publish-artifacts.yml
    with:
      versionNumber: ${{ needs.release.outputs.VersionNumber }}

  DEV:
    name: DEV
    needs:
      - release
      - buildandpublish
    uses: ./.github/workflows/deploy.yml
    with:
      applicationName: funky-iso
      location: australiasoutheast
      versionNumber: ${{ needs.release.outputs.VersionNumber }}
      environment: dev
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}