name: "letsdoit.isolated.functions"
concurrency: letsdoit.isolated.functions

on:
  push:
    paths:
      - 'src/Azure/**'     
      - '.github/workflows/**'
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            
      - name: Restore .NET Tools        
        run: dotnet tool restore
        
      - name: Check C# Code Formatting
        run: dotnet csharpier . --check
        
      - name: Restore Dependencies
        run: dotnet restore src/Azure/IsolatedFunctions/IsolatedFunctions.csproj
        
      - name: Build Project
        run: dotnet build --configuration Release --no-restore src/Azure/IsolatedFunctions/IsolatedFunctions.csproj
        
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
      - name: Create Artifact
        shell: bash
        run: dotnet publish -c Release --no-build src/Azure/IsolatedFunctions/IsolatedFunctions.csproj -o ${{ env.BUILD_VERSION }}
        
      - name: Publish Artifact - Function App
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_VERSION }}
          path: ${{ env.BUILD_VERSION }}/**
          if-no-files-found: error

      - name: Publish Artifact - Templates
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: ./.github/bicep
          if-no-files-found: error
    
    outputs:
      artifactName: ${{ env.BUILD_VERSION }}
  
  
#  restoreandbuild:
#    needs: 
#      - build
#    name: Restore and Build    
#    uses: ./.github/workflows/restore-and-build.yml
#    with:
#      project-path: src/Azure/IsolatedFunctions/IsolatedFunctions.csproj
#      
#  buildversionnumber:
#    runs-on: ubuntu-latest
#    needs: 
#      - restoreandbuild
#    steps:
#      - name: Build Version Number
#        shell: bash
#        run: |
#          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
#      
#    outputs: 
#      versionNumber: ${{ env.BUILD_VERSION }}
#      
#  DEV:
#    name: DEV
#    needs: 
#      - buildversionnumber
#    uses: ./.github/workflows/deploy.yml
#    with:
#      applicationName: funky-iso
#      location: australiasoutheast
#      versionNumber: ${{ needs.buildversionnumber.outputs.versionNumber }}
#      environment: dev
#    secrets: 
#      credentials: ${{ secrets.AZURE_CREDENTIALS }}
#      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}