name: "letsdoit.isolated.functions"
concurrency: letsdoit.isolated.functions

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'Azure/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-name:
          - IsolatedFunctions
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Restore
        run: dotnet restore src/Azure/${{ matrix.project-name }}/${{ matrix.project-name }}.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore src/Azure/${{ matrix.project-name }}/${{ matrix.project-name }}.csproj