name: Isolated Functions
concurrency: Isolated Functions

on:
  push:
    paths:
      - 'src/**'     
      - '.github/**'

jobs:  
  build:
    name: CI Validations
    uses: ./.github/workflows/ci-validation-checks.yml