name: "letsdoit.isolated.functions"
concurrency: letsdoit.isolated.functions

on:
  push:
    paths:
      - 'src/Azure/**'     
      - '.github/workflows/**'
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-name:
          - IsolatedFunctions
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            
      - name: Run CSharpier        
        uses: ../.github/workflows/./check-code-format.yml
        
      - name: Restore Dependencies
        run: dotnet restore src/Azure/${{ matrix.project-name }}/${{ matrix.project-name }}.csproj
        
      - name: Build
        run: dotnet build --configuration Release --no-restore src/Azure/${{ matrix.project-name }}/${{ matrix.project-name }}.csproj