name: isolated_functions
concurrency: isolated_functions

on:
  push:
    paths:
      - 'src/**'     
      - '.github/**'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CI Validations        
        uses: ./.github/workflows/ci-validation-checks.yml