name: ci_validations

on:
  workflow_call:

jobs:
  civalidations:
    name: CI Validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Check C# Code Formatting
        run: dotnet csharpier . --check