name: CI Validations

on:
  workflow_call:

jobs:
  checklist:
    name: Checklist
    runs-on: ubuntu-latest
    strategy: 
        matrix:
            project-name:
            - IsolatedFunctions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Check C# Code Formatting
        run: dotnet csharpier . --check
        
      - name: Restore Dependencies
        run: dotnet restore tests/${{matrix.project-name}}.Tests/${{matrix.project-name}}.Tests.csproj

      - name: Build Project
        run: dotnet build --configuration Release --no-restore tests/${{matrix.project-name}}.Tests/${{matrix.project-name}}.Tests.csproj
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" tests/${{matrix.project-name}}.Tests/${{matrix.project-name}}.Tests.csproj