name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_latest_tag
        uses: actions/github-script@v6
        with:
          script: |
            const latestTag = await github.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            const tag = latestTag.data[0].name;
            console.log("Latest tag: ", tag);
            return tag;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}