name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
        
jobs:
  release:
    name: Tag and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            
      - name: Restore Dependencies
        run: dotnet restore src/Azure/IsolatedFunctions/IsolatedFunctions.csproj

      - name: Build Project
        run: dotnet build --configuration Release --no-restore src/Azure/IsolatedFunctions/IsolatedFunctions.csproj            
        
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BRANCH: main
          DEFAULT_BUMP: ${{ inputs.release_type }}
          
      - name: Create Artifact
        shell: bash
        run: dotnet publish -c Release --no-build src/Azure/IsolatedFunctions/IsolatedFunctions.csproj -o ${{ steps.bump.outputs.new_tag }}
        
      - name: Publish Artifact - Function App
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.bump.outputs.new_tag }}
          path: ${{ steps.bump.outputs.new_tag }}/**
          if-no-files-found: error        
          
      - name: Publish Artifact - Templates
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: ./.github/bicep
          if-no-files-found: error
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.bump.outputs.new_tag }}
          
    outputs:
      VersionNumber: ${{ steps.bump.outputs.new_tag }}
        
  DEV:
    name: DEV
    needs:
      - release
    uses: ./.github/workflows/deploy.yml
    with:
      applicationName: funky-iso
      location: australiasoutheast
      versionNumber: ${{ needs.release.outputs.VersionNumber }}
      environment: dev
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}        
        
      

      