name: provisionresources

on:
  workflow_call:
    inputs:
      applicationName:
        type: string
        required: true
        description: Application name
        
      environment:
        type: string
        required: true
        description: Environment name
      
      location:
        type: string
        required: true
        description: Resource group location
      
      versionNumber:
        type: string
        required: true
        description: Version number to track deployments
        
    secrets:
      subscriptionId:
        required: true
        description: Azure subscription id
      credentials:
        required: true
        description: Azure service principal details used to provision Azure resources
        
jobs:
  provisioning:
    name: Provisioning
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'       
      
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: deploy
          
      - name: Download Application Binaries
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.versionNumber }}
          path: ${{ inputs.versionNumber }}
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.credentials }}
          
      - name: Provision Azure Resources
        uses: azure/arm-deploy@v1
        with:
          failOnStdErr: false
          deploymentName: ${{ env.ARTIFACT_NAME }}
          scope: subscription
          region: ${{ inputs.location }}
          subscriptionId: ${{ secrets.subscriptionId }}
          template: deploy/main.bicep
          parameters: >
            appName=${{ inputs.applicationName }}
            version=${{ inputs.versionNumber }}
            environment=${{ inputs.environment }}
            location=${{ inputs.location }}
            
      - name: "Deploy Azure Function App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }}'
          package: ${{ inputs.versionNumber }}

      - name: Logout from Azure
        uses: Azure/CLI@v1
        with:
          inlineScript:
            az logout                  
            
            